FROM caddy:builder AS builder

RUN xcaddy build \
    --with github.com/greenpau/caddy-auth-portal \
    --with github.com/greenpau/caddy-authorize

FROM caddy:2.7.6

COPY --from=builder /usr/bin/caddy /usr/bin/caddy
